### ISSUE TITLE
Подготовить структуру проекта Django

### ISSUE THREAD

**Issue by vikseal** [Environmentally-friendly-products-store/meeco-backend#2]
Создать приложение Django
Создать приложение users, products, events, orders, api, core
Добавить приложения в settings.py
Установить DRF
Установить пакеты фильтров для DRF
Установить dotenv у подготовить настройку для

POSTGRES_DB=
POSTGRES_USER=
POSTGRES_PASSWORD=

DB_HOST=
DB_PORT=

SECRET_KEY=
ALLOWED_HOSTS=

DEBUG=True

Создать requirements.txt

**Comment by MultikPatin** [comment]
Создать приложение core

Установить пакеты фильтров для DRF
Установить dotenv у подготовить настройку для Postgres

POSTGRES_DB=
POSTGRES_USER=
POSTGRES_PASSWORD=

DB_HOST=
DB_PORT=

SECRET_KEY=
ALLOWED_HOSTS=

DEBUG=True
